feat(arkhn): add practitioner id to hapi requests header
arkhn-oss/Cohort360 pull request #13
Opened 2021-03-22 14:44 UTC by tevariou

2021-03-22 15:33 UTC, simonvadee approved these changes

2021-03-22 15:50 UTC, simonvadee requested changes

2021-03-22 15:50 UTC, simonvadee commented on src/state/me.ts
> +        localStorage.setItem(PRACTITIONER_ID, practitioner.id)
you forgot to remove it on logout

2021-03-22 16:31 UTC, BPierrick commented on src/services/api.js
> +// api.interceptors.request.use((config) => {
Don't we need to keep interceptors?
`api` is instantiated before login right?

2021-03-23 10:01 UTC, simonvadee approved these changes

2021-03-23 11:43 UTC, BPierrick commented
Could we merge this PR directly into `demo` branch ?

I'd need its changes to progress on #12

2021-03-23 12:33 UTC, merged